// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: protos/external.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackerGetStatusResponse_TrackerState int32

const (
	TrackerGetStatusResponse_IDLE        TrackerGetStatusResponse_TrackerState = 0
	TrackerGetStatusResponse_CALIBRATING TrackerGetStatusResponse_TrackerState = 1
	TrackerGetStatusResponse_TRACKING    TrackerGetStatusResponse_TrackerState = 2
)

// Enum value maps for TrackerGetStatusResponse_TrackerState.
var (
	TrackerGetStatusResponse_TrackerState_name = map[int32]string{
		0: "IDLE",
		1: "CALIBRATING",
		2: "TRACKING",
	}
	TrackerGetStatusResponse_TrackerState_value = map[string]int32{
		"IDLE":        0,
		"CALIBRATING": 1,
		"TRACKING":    2,
	}
)

func (x TrackerGetStatusResponse_TrackerState) Enum() *TrackerGetStatusResponse_TrackerState {
	p := new(TrackerGetStatusResponse_TrackerState)
	*p = x
	return p
}

func (x TrackerGetStatusResponse_TrackerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackerGetStatusResponse_TrackerState) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_external_proto_enumTypes[0].Descriptor()
}

func (TrackerGetStatusResponse_TrackerState) Type() protoreflect.EnumType {
	return &file_protos_external_proto_enumTypes[0]
}

func (x TrackerGetStatusResponse_TrackerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackerGetStatusResponse_TrackerState.Descriptor instead.
func (TrackerGetStatusResponse_TrackerState) EnumDescriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{14, 0}
}

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// Types that are assignable to Message:
	//
	//	*Packet_Request
	//	*Packet_Response
	Message isPacket_Message `protobuf_oneof:"message"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (m *Packet) GetMessage() isPacket_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *Packet) GetRequest() *Request {
	if x, ok := x.GetMessage().(*Packet_Request); ok {
		return x.Request
	}
	return nil
}

func (x *Packet) GetResponse() *Response {
	if x, ok := x.GetMessage().(*Packet_Response); ok {
		return x.Response
	}
	return nil
}

type isPacket_Message interface {
	isPacket_Message()
}

type Packet_Request struct {
	Request *Request `protobuf:"bytes,10,opt,name=request,proto3,oneof"`
}

type Packet_Response struct {
	Response *Response `protobuf:"bytes,11,opt,name=response,proto3,oneof"`
}

func (*Packet_Request) isPacket_Message() {}

func (*Packet_Response) isPacket_Message() {}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*Request_HelloRequest
	//	*Request_DisplaySceneRequest
	//	*Request_GetAssetRequest
	//	*Request_GetTableConfigurationRequest
	//	*Request_GetCurrentSceneRequest
	//	*Request_TrackerGetStatusRequest
	//	*Request_TrackerSetIdleRequest
	//	*Request_TrackerStartCalibrationRequest
	//	*Request_TrackerGetCalibrationRequest
	//	*Request_TrackerStartTrackingRequest
	//	*Request_TrackerGetMarkerLocationRequest
	//	*Request_TrackerUpdateMarkerLocationRequest
	Message isRequest_Message `protobuf_oneof:"message"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{1}
}

func (m *Request) GetMessage() isRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *Request) GetHelloRequest() *HelloRequest {
	if x, ok := x.GetMessage().(*Request_HelloRequest); ok {
		return x.HelloRequest
	}
	return nil
}

func (x *Request) GetDisplaySceneRequest() *DisplaySceneRequest {
	if x, ok := x.GetMessage().(*Request_DisplaySceneRequest); ok {
		return x.DisplaySceneRequest
	}
	return nil
}

func (x *Request) GetGetAssetRequest() *GetAssetRequest {
	if x, ok := x.GetMessage().(*Request_GetAssetRequest); ok {
		return x.GetAssetRequest
	}
	return nil
}

func (x *Request) GetGetTableConfigurationRequest() *GetTableConfigurationRequest {
	if x, ok := x.GetMessage().(*Request_GetTableConfigurationRequest); ok {
		return x.GetTableConfigurationRequest
	}
	return nil
}

func (x *Request) GetGetCurrentSceneRequest() *GetCurrentSceneRequest {
	if x, ok := x.GetMessage().(*Request_GetCurrentSceneRequest); ok {
		return x.GetCurrentSceneRequest
	}
	return nil
}

func (x *Request) GetTrackerGetStatusRequest() *TrackerGetStatusRequest {
	if x, ok := x.GetMessage().(*Request_TrackerGetStatusRequest); ok {
		return x.TrackerGetStatusRequest
	}
	return nil
}

func (x *Request) GetTrackerSetIdleRequest() *TrackerSetIdleRequest {
	if x, ok := x.GetMessage().(*Request_TrackerSetIdleRequest); ok {
		return x.TrackerSetIdleRequest
	}
	return nil
}

func (x *Request) GetTrackerStartCalibrationRequest() *TrackerStartCalibrationRequest {
	if x, ok := x.GetMessage().(*Request_TrackerStartCalibrationRequest); ok {
		return x.TrackerStartCalibrationRequest
	}
	return nil
}

func (x *Request) GetTrackerGetCalibrationRequest() *TrackerGetCalibrationRequest {
	if x, ok := x.GetMessage().(*Request_TrackerGetCalibrationRequest); ok {
		return x.TrackerGetCalibrationRequest
	}
	return nil
}

func (x *Request) GetTrackerStartTrackingRequest() *TrackerStartTrackingRequest {
	if x, ok := x.GetMessage().(*Request_TrackerStartTrackingRequest); ok {
		return x.TrackerStartTrackingRequest
	}
	return nil
}

func (x *Request) GetTrackerGetMarkerLocationRequest() *TrackerGetMarkerLocationRequest {
	if x, ok := x.GetMessage().(*Request_TrackerGetMarkerLocationRequest); ok {
		return x.TrackerGetMarkerLocationRequest
	}
	return nil
}

func (x *Request) GetTrackerUpdateMarkerLocationRequest() *TrackerUpdateMarkerLocationRequest {
	if x, ok := x.GetMessage().(*Request_TrackerUpdateMarkerLocationRequest); ok {
		return x.TrackerUpdateMarkerLocationRequest
	}
	return nil
}

type isRequest_Message interface {
	isRequest_Message()
}

type Request_HelloRequest struct {
	// Respond with AckResponse
	HelloRequest *HelloRequest `protobuf:"bytes,1,opt,name=helloRequest,proto3,oneof"`
}

type Request_DisplaySceneRequest struct {
	// Respond with AckResponse
	DisplaySceneRequest *DisplaySceneRequest `protobuf:"bytes,2,opt,name=displaySceneRequest,proto3,oneof"`
}

type Request_GetAssetRequest struct {
	// Respond with GetAssetResponse
	GetAssetRequest *GetAssetRequest `protobuf:"bytes,3,opt,name=getAssetRequest,proto3,oneof"`
}

type Request_GetTableConfigurationRequest struct {
	// Respond with GetTableConfigurationResponse
	GetTableConfigurationRequest *GetTableConfigurationRequest `protobuf:"bytes,4,opt,name=getTableConfigurationRequest,proto3,oneof"`
}

type Request_GetCurrentSceneRequest struct {
	// Respond with GetCurrentSceneResponse
	GetCurrentSceneRequest *GetCurrentSceneRequest `protobuf:"bytes,5,opt,name=getCurrentSceneRequest,proto3,oneof"`
}

type Request_TrackerGetStatusRequest struct {
	// Respond with TrackerGetStatusResponse
	TrackerGetStatusRequest *TrackerGetStatusRequest `protobuf:"bytes,10,opt,name=trackerGetStatusRequest,proto3,oneof"`
}

type Request_TrackerSetIdleRequest struct {
	// Respond with AckResponse
	TrackerSetIdleRequest *TrackerSetIdleRequest `protobuf:"bytes,11,opt,name=trackerSetIdleRequest,proto3,oneof"`
}

type Request_TrackerStartCalibrationRequest struct {
	// Respond with AckResponse
	TrackerStartCalibrationRequest *TrackerStartCalibrationRequest `protobuf:"bytes,12,opt,name=trackerStartCalibrationRequest,proto3,oneof"`
}

type Request_TrackerGetCalibrationRequest struct {
	// Respond with TrackerGetCalibrationResponse
	TrackerGetCalibrationRequest *TrackerGetCalibrationRequest `protobuf:"bytes,13,opt,name=trackerGetCalibrationRequest,proto3,oneof"`
}

type Request_TrackerStartTrackingRequest struct {
	// Respond with AckResponse
	TrackerStartTrackingRequest *TrackerStartTrackingRequest `protobuf:"bytes,14,opt,name=trackerStartTrackingRequest,proto3,oneof"`
}

type Request_TrackerGetMarkerLocationRequest struct {
	// Respond with TrackerGetMarkerLocationResponse
	TrackerGetMarkerLocationRequest *TrackerGetMarkerLocationRequest `protobuf:"bytes,15,opt,name=trackerGetMarkerLocationRequest,proto3,oneof"`
}

type Request_TrackerUpdateMarkerLocationRequest struct {
	// Don't respond
	TrackerUpdateMarkerLocationRequest *TrackerUpdateMarkerLocationRequest `protobuf:"bytes,16,opt,name=trackerUpdateMarkerLocationRequest,proto3,oneof"`
}

func (*Request_HelloRequest) isRequest_Message() {}

func (*Request_DisplaySceneRequest) isRequest_Message() {}

func (*Request_GetAssetRequest) isRequest_Message() {}

func (*Request_GetTableConfigurationRequest) isRequest_Message() {}

func (*Request_GetCurrentSceneRequest) isRequest_Message() {}

func (*Request_TrackerGetStatusRequest) isRequest_Message() {}

func (*Request_TrackerSetIdleRequest) isRequest_Message() {}

func (*Request_TrackerStartCalibrationRequest) isRequest_Message() {}

func (*Request_TrackerGetCalibrationRequest) isRequest_Message() {}

func (*Request_TrackerStartTrackingRequest) isRequest_Message() {}

func (*Request_TrackerGetMarkerLocationRequest) isRequest_Message() {}

func (*Request_TrackerUpdateMarkerLocationRequest) isRequest_Message() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*Response_AckResponse
	//	*Response_GetAssetResponse
	//	*Response_GetTableConfigurationResponse
	//	*Response_GetCurrentSceneResponse
	//	*Response_TrackerGetStatusResponse
	//	*Response_TrackerGetCalibrationResponse
	//	*Response_TrackerGetMarkerLocationResponse
	Message isResponse_Message `protobuf_oneof:"message"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{2}
}

func (m *Response) GetMessage() isResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *Response) GetAckResponse() *AckResponse {
	if x, ok := x.GetMessage().(*Response_AckResponse); ok {
		return x.AckResponse
	}
	return nil
}

func (x *Response) GetGetAssetResponse() *GetAssetResponse {
	if x, ok := x.GetMessage().(*Response_GetAssetResponse); ok {
		return x.GetAssetResponse
	}
	return nil
}

func (x *Response) GetGetTableConfigurationResponse() *GetTableConfigurationResponse {
	if x, ok := x.GetMessage().(*Response_GetTableConfigurationResponse); ok {
		return x.GetTableConfigurationResponse
	}
	return nil
}

func (x *Response) GetGetCurrentSceneResponse() *GetCurrentSceneResponse {
	if x, ok := x.GetMessage().(*Response_GetCurrentSceneResponse); ok {
		return x.GetCurrentSceneResponse
	}
	return nil
}

func (x *Response) GetTrackerGetStatusResponse() *TrackerGetStatusResponse {
	if x, ok := x.GetMessage().(*Response_TrackerGetStatusResponse); ok {
		return x.TrackerGetStatusResponse
	}
	return nil
}

func (x *Response) GetTrackerGetCalibrationResponse() *TrackerGetCalibrationResponse {
	if x, ok := x.GetMessage().(*Response_TrackerGetCalibrationResponse); ok {
		return x.TrackerGetCalibrationResponse
	}
	return nil
}

func (x *Response) GetTrackerGetMarkerLocationResponse() *TrackerGetMarkerLocationResponse {
	if x, ok := x.GetMessage().(*Response_TrackerGetMarkerLocationResponse); ok {
		return x.TrackerGetMarkerLocationResponse
	}
	return nil
}

type isResponse_Message interface {
	isResponse_Message()
}

type Response_AckResponse struct {
	AckResponse *AckResponse `protobuf:"bytes,1,opt,name=ackResponse,proto3,oneof"`
}

type Response_GetAssetResponse struct {
	GetAssetResponse *GetAssetResponse `protobuf:"bytes,2,opt,name=getAssetResponse,proto3,oneof"`
}

type Response_GetTableConfigurationResponse struct {
	GetTableConfigurationResponse *GetTableConfigurationResponse `protobuf:"bytes,3,opt,name=getTableConfigurationResponse,proto3,oneof"`
}

type Response_GetCurrentSceneResponse struct {
	GetCurrentSceneResponse *GetCurrentSceneResponse `protobuf:"bytes,4,opt,name=getCurrentSceneResponse,proto3,oneof"`
}

type Response_TrackerGetStatusResponse struct {
	// ------- Tracker ------- //
	TrackerGetStatusResponse *TrackerGetStatusResponse `protobuf:"bytes,10,opt,name=trackerGetStatusResponse,proto3,oneof"`
}

type Response_TrackerGetCalibrationResponse struct {
	TrackerGetCalibrationResponse *TrackerGetCalibrationResponse `protobuf:"bytes,11,opt,name=trackerGetCalibrationResponse,proto3,oneof"`
}

type Response_TrackerGetMarkerLocationResponse struct {
	TrackerGetMarkerLocationResponse *TrackerGetMarkerLocationResponse `protobuf:"bytes,12,opt,name=trackerGetMarkerLocationResponse,proto3,oneof"`
}

func (*Response_AckResponse) isResponse_Message() {}

func (*Response_GetAssetResponse) isResponse_Message() {}

func (*Response_GetTableConfigurationResponse) isResponse_Message() {}

func (*Response_GetCurrentSceneResponse) isResponse_Message() {}

func (*Response_TrackerGetStatusResponse) isResponse_Message() {}

func (*Response_TrackerGetCalibrationResponse) isResponse_Message() {}

func (*Response_TrackerGetMarkerLocationResponse) isResponse_Message() {}

type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{3}
}

type AckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{4}
}

type DisplaySceneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scene *Scene `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
}

func (x *DisplaySceneRequest) Reset() {
	*x = DisplaySceneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisplaySceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplaySceneRequest) ProtoMessage() {}

func (x *DisplaySceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplaySceneRequest.ProtoReflect.Descriptor instead.
func (*DisplaySceneRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{5}
}

func (x *DisplaySceneRequest) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

type GetAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{6}
}

func (x *GetAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload   []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	MediaType string `protobuf:"bytes,3,opt,name=mediaType,proto3" json:"mediaType,omitempty"`
}

func (x *GetAssetResponse) Reset() {
	*x = GetAssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetResponse) ProtoMessage() {}

func (x *GetAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetResponse.ProtoReflect.Descriptor instead.
func (*GetAssetResponse) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{7}
}

func (x *GetAssetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAssetResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetAssetResponse) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type GetTableConfigurationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTableConfigurationRequest) Reset() {
	*x = GetTableConfigurationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTableConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableConfigurationRequest) ProtoMessage() {}

func (x *GetTableConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetTableConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{8}
}

type GetTableConfigurationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resolution *GetTableConfigurationResponse_Resolution `protobuf:"bytes,1,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Size       float64                                   `protobuf:"fixed64,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *GetTableConfigurationResponse) Reset() {
	*x = GetTableConfigurationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTableConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableConfigurationResponse) ProtoMessage() {}

func (x *GetTableConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetTableConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{9}
}

func (x *GetTableConfigurationResponse) GetResolution() *GetTableConfigurationResponse_Resolution {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *GetTableConfigurationResponse) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetCurrentSceneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCurrentSceneRequest) Reset() {
	*x = GetCurrentSceneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSceneRequest) ProtoMessage() {}

func (x *GetCurrentSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSceneRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentSceneRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{10}
}

type GetCurrentSceneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scene *Scene `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
}

func (x *GetCurrentSceneResponse) Reset() {
	*x = GetCurrentSceneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSceneResponse) ProtoMessage() {}

func (x *GetCurrentSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSceneResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentSceneResponse) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{11}
}

func (x *GetCurrentSceneResponse) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

type TrackerGetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackerGetStatusRequest) Reset() {
	*x = TrackerGetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackerGetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerGetStatusRequest) ProtoMessage() {}

func (x *TrackerGetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerGetStatusRequest.ProtoReflect.Descriptor instead.
func (*TrackerGetStatusRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{12}
}

type TrackerVector2D struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *TrackerVector2D) Reset() {
	*x = TrackerVector2D{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackerVector2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerVector2D) ProtoMessage() {}

func (x *TrackerVector2D) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerVector2D.ProtoReflect.Descriptor instead.
func (*TrackerVector2D) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{13}
}

func (x *TrackerVector2D) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TrackerVector2D) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type TrackerGetStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string                                `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Version string                                `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	State   TrackerGetStatusResponse_TrackerState `protobuf:"varint,5,opt,name=state,proto3,enum=TrackerGetStatusResponse_TrackerState" json:"state,omitempty"`
}

func (x *TrackerGetStatusResponse) Reset() {
	*x = TrackerGetStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackerGetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerGetStatusResponse) ProtoMessage() {}

func (x *TrackerGetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerGetStatusResponse.ProtoReflect.Descriptor instead.
func (*TrackerGetStatusResponse) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{14}
}

func (x *TrackerGetStatusResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TrackerGetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TrackerGetStatusResponse) GetState() TrackerGetStatusResponse_TrackerState {
	if x != nil {
		return x.State
	}
	return TrackerGetStatusResponse_IDLE
}

type TrackerSetIdleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackerSetIdleRequest) Reset() {
	*x = TrackerSetIdleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackerSetIdleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerSetIdleRequest) ProtoMessage() {}

func (x *TrackerSetIdleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerSetIdleRequest.ProtoReflect.Descriptor instead.
func (*TrackerSetIdleRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{15}
}

type TrackerStartCalibrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Corners []*TrackerVector2D `protobuf:"bytes,1,rep,name=corners,proto3" json:"corners,omitempty"`
}

func (x *TrackerStartCalibrationRequest) Reset() {
	*x = TrackerStartCalibrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackerStartCalibrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerStartCalibrationRequest) ProtoMessage() {}

func (x *TrackerStartCalibrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerStartCalibrationRequest.ProtoReflect.Descriptor instead.
func (*TrackerStartCalibrationRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{16}
}

func (x *TrackerStartCalibrationRequest) GetCorners() []*TrackerVector2D {
	if x != nil {
		return x.Corners
	}
	return nil
}

type TrackerGetCalibrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackerGetCalibrationRequest) Reset() {
	*x = TrackerGetCalibrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackerGetCalibrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerGetCalibrationRequest) ProtoMessage() {}

func (x *TrackerGetCalibrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerGetCalibrationRequest.ProtoReflect.Descriptor instead.
func (*TrackerGetCalibrationRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{17}
}

type TrackerGetCalibrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FoundCorners    []int32            `protobuf:"varint,1,rep,packed,name=foundCorners,proto3" json:"foundCorners,omitempty"`
	CornerLocations []*TrackerVector2D `protobuf:"bytes,2,rep,name=cornerLocations,proto3" json:"cornerLocations,omitempty"`
}

func (x *TrackerGetCalibrationResponse) Reset() {
	*x = TrackerGetCalibrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackerGetCalibrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerGetCalibrationResponse) ProtoMessage() {}

func (x *TrackerGetCalibrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerGetCalibrationResponse.ProtoReflect.Descriptor instead.
func (*TrackerGetCalibrationResponse) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{18}
}

func (x *TrackerGetCalibrationResponse) GetFoundCorners() []int32 {
	if x != nil {
		return x.FoundCorners
	}
	return nil
}

func (x *TrackerGetCalibrationResponse) GetCornerLocations() []*TrackerVector2D {
	if x != nil {
		return x.CornerLocations
	}
	return nil
}

type TrackerStartTrackingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateRateMs float32 `protobuf:"fixed32,1,opt,name=updateRateMs,proto3" json:"updateRateMs,omitempty"`
}

func (x *TrackerStartTrackingRequest) Reset() {
	*x = TrackerStartTrackingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackerStartTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerStartTrackingRequest) ProtoMessage() {}

func (x *TrackerStartTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerStartTrackingRequest.ProtoReflect.Descriptor instead.
func (*TrackerStartTrackingRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{19}
}

func (x *TrackerStartTrackingRequest) GetUpdateRateMs() float32 {
	if x != nil {
		return x.UpdateRateMs
	}
	return 0
}

type TrackerGetMarkerLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackerGetMarkerLocationRequest) Reset() {
	*x = TrackerGetMarkerLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackerGetMarkerLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerGetMarkerLocationRequest) ProtoMessage() {}

func (x *TrackerGetMarkerLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerGetMarkerLocationRequest.ProtoReflect.Descriptor instead.
func (*TrackerGetMarkerLocationRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{20}
}

type TrackerGetMarkerLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarkerLocations map[int32]*TrackerVector2D `protobuf:"bytes,1,rep,name=markerLocations,proto3" json:"markerLocations,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TrackerGetMarkerLocationResponse) Reset() {
	*x = TrackerGetMarkerLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackerGetMarkerLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerGetMarkerLocationResponse) ProtoMessage() {}

func (x *TrackerGetMarkerLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerGetMarkerLocationResponse.ProtoReflect.Descriptor instead.
func (*TrackerGetMarkerLocationResponse) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{21}
}

func (x *TrackerGetMarkerLocationResponse) GetMarkerLocations() map[int32]*TrackerVector2D {
	if x != nil {
		return x.MarkerLocations
	}
	return nil
}

type TrackerUpdateMarkerLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarkerLocations map[int32]*TrackerVector2D `protobuf:"bytes,1,rep,name=markerLocations,proto3" json:"markerLocations,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TrackerUpdateMarkerLocationRequest) Reset() {
	*x = TrackerUpdateMarkerLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackerUpdateMarkerLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerUpdateMarkerLocationRequest) ProtoMessage() {}

func (x *TrackerUpdateMarkerLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerUpdateMarkerLocationRequest.ProtoReflect.Descriptor instead.
func (*TrackerUpdateMarkerLocationRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{22}
}

func (x *TrackerUpdateMarkerLocationRequest) GetMarkerLocations() map[int32]*TrackerVector2D {
	if x != nil {
		return x.MarkerLocations
	}
	return nil
}

type GetTableConfigurationResponse_Resolution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  float64 `protobuf:"fixed64,1,opt,name=width,proto3" json:"width,omitempty"`
	Height float64 `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GetTableConfigurationResponse_Resolution) Reset() {
	*x = GetTableConfigurationResponse_Resolution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTableConfigurationResponse_Resolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableConfigurationResponse_Resolution) ProtoMessage() {}

func (x *GetTableConfigurationResponse_Resolution) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableConfigurationResponse_Resolution.ProtoReflect.Descriptor instead.
func (*GetTableConfigurationResponse_Resolution) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetTableConfigurationResponse_Resolution) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetTableConfigurationResponse_Resolution) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_protos_external_proto protoreflect.FileDescriptor

var file_protos_external_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x01, 0x0a, 0x06,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xc6,
	0x08, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x0c, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x0c, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x48, 0x0a, 0x13, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x44,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x13, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0f, 0x67, 0x65, 0x74,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x63, 0x0a, 0x1c, 0x67, 0x65, 0x74, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x1c,
	0x67, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x51, 0x0a, 0x16,
	0x67, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x16, 0x67, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x54, 0x0a, 0x17, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x17, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4e, 0x0a, 0x15, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x53, 0x65, 0x74, 0x49, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x65,
	0x74, 0x49, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x15,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x74, 0x49, 0x64, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x69, 0x0a, 0x1e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x61, 0x6c, 0x69,
	0x62, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x1e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x61,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x63, 0x0a, 0x1c, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x1c, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x60, 0x0a, 0x1b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x1b, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x6c, 0x0a, 0x1f, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x65, 0x72, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x1f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74,
	0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x75, 0x0a, 0x22, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x22, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xf8, 0x04, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x10, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x1d, 0x67, 0x65, 0x74, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x1d, 0x67, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x54, 0x0a, 0x17, 0x67, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x17, 0x67, 0x65,
	0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x18, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x00, 0x52, 0x18, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66,
	0x0a, 0x1d, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6c, 0x69,
	0x62, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x1d, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a, 0x20, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x20, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x65,
	0x74, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x33, 0x0a, 0x13, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x63, 0x65, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52,
	0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5a, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x54, 0x79, 0x70, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xba, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x1a, 0x3a, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x05,
	0x73, 0x63, 0x65, 0x6e, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x2d, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x32, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22,
	0xbf, 0x01, 0x0a, 0x18, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x37, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x44, 0x4c, 0x45,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x41, 0x4c, 0x49, 0x42, 0x52, 0x41, 0x54, 0x49, 0x4e,
	0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x52, 0x41, 0x43, 0x4b, 0x49, 0x4e, 0x47, 0x10,
	0x02, 0x22, 0x17, 0x0a, 0x15, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x74, 0x49,
	0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x1e, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x61, 0x6c, 0x69, 0x62, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07,
	0x63, 0x6f, 0x72, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x64, 0x52,
	0x07, 0x63, 0x6f, 0x72, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x1e, 0x0a, 0x1c, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x7f, 0x0a, 0x1d, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x6f, 0x75,
	0x6e, 0x64, 0x43, 0x6f, 0x72, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x0c, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x72, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x3a, 0x0a,
	0x0f, 0x63, 0x6f, 0x72, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x64, 0x52, 0x0f, 0x63, 0x6f, 0x72, 0x6e, 0x65, 0x72,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x41, 0x0a, 0x1b, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x22, 0x21, 0x0a, 0x1f,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0xda, 0x01, 0x0a, 0x20, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4d, 0x61,
	0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x0f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x54, 0x0a, 0x14, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32,
	0x64, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xde, 0x01, 0x0a,
	0x22, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61,
	0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x62, 0x0a, 0x0f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b,
	0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x54, 0x0a, 0x14, 0x4d, 0x61, 0x72, 0x6b, 0x65,
	0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x32, 0x64, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x32, 0x5a,
	0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x75, 0x74, 0x6d,
	0x61, 0x6e, 0x39, 0x36, 0x2f, 0x66, 0x61, 0x6e, 0x74, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2e,
	0x69, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_external_proto_rawDescOnce sync.Once
	file_protos_external_proto_rawDescData = file_protos_external_proto_rawDesc
)

func file_protos_external_proto_rawDescGZIP() []byte {
	file_protos_external_proto_rawDescOnce.Do(func() {
		file_protos_external_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_external_proto_rawDescData)
	})
	return file_protos_external_proto_rawDescData
}

var file_protos_external_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_external_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_protos_external_proto_goTypes = []interface{}{
	(TrackerGetStatusResponse_TrackerState)(0), // 0: TrackerGetStatusResponse.TrackerState
	(*Packet)(nil),                                   // 1: Packet
	(*Request)(nil),                                  // 2: Request
	(*Response)(nil),                                 // 3: Response
	(*HelloRequest)(nil),                             // 4: HelloRequest
	(*AckResponse)(nil),                              // 5: AckResponse
	(*DisplaySceneRequest)(nil),                      // 6: DisplaySceneRequest
	(*GetAssetRequest)(nil),                          // 7: GetAssetRequest
	(*GetAssetResponse)(nil),                         // 8: GetAssetResponse
	(*GetTableConfigurationRequest)(nil),             // 9: GetTableConfigurationRequest
	(*GetTableConfigurationResponse)(nil),            // 10: GetTableConfigurationResponse
	(*GetCurrentSceneRequest)(nil),                   // 11: GetCurrentSceneRequest
	(*GetCurrentSceneResponse)(nil),                  // 12: GetCurrentSceneResponse
	(*TrackerGetStatusRequest)(nil),                  // 13: TrackerGetStatusRequest
	(*TrackerVector2D)(nil),                          // 14: TrackerVector2d
	(*TrackerGetStatusResponse)(nil),                 // 15: TrackerGetStatusResponse
	(*TrackerSetIdleRequest)(nil),                    // 16: TrackerSetIdleRequest
	(*TrackerStartCalibrationRequest)(nil),           // 17: TrackerStartCalibrationRequest
	(*TrackerGetCalibrationRequest)(nil),             // 18: TrackerGetCalibrationRequest
	(*TrackerGetCalibrationResponse)(nil),            // 19: TrackerGetCalibrationResponse
	(*TrackerStartTrackingRequest)(nil),              // 20: TrackerStartTrackingRequest
	(*TrackerGetMarkerLocationRequest)(nil),          // 21: TrackerGetMarkerLocationRequest
	(*TrackerGetMarkerLocationResponse)(nil),         // 22: TrackerGetMarkerLocationResponse
	(*TrackerUpdateMarkerLocationRequest)(nil),       // 23: TrackerUpdateMarkerLocationRequest
	(*GetTableConfigurationResponse_Resolution)(nil), // 24: GetTableConfigurationResponse.Resolution
	nil,           // 25: TrackerGetMarkerLocationResponse.MarkerLocationsEntry
	nil,           // 26: TrackerUpdateMarkerLocationRequest.MarkerLocationsEntry
	(*Scene)(nil), // 27: Scene
}
var file_protos_external_proto_depIdxs = []int32{
	2,  // 0: Packet.request:type_name -> Request
	3,  // 1: Packet.response:type_name -> Response
	4,  // 2: Request.helloRequest:type_name -> HelloRequest
	6,  // 3: Request.displaySceneRequest:type_name -> DisplaySceneRequest
	7,  // 4: Request.getAssetRequest:type_name -> GetAssetRequest
	9,  // 5: Request.getTableConfigurationRequest:type_name -> GetTableConfigurationRequest
	11, // 6: Request.getCurrentSceneRequest:type_name -> GetCurrentSceneRequest
	13, // 7: Request.trackerGetStatusRequest:type_name -> TrackerGetStatusRequest
	16, // 8: Request.trackerSetIdleRequest:type_name -> TrackerSetIdleRequest
	17, // 9: Request.trackerStartCalibrationRequest:type_name -> TrackerStartCalibrationRequest
	18, // 10: Request.trackerGetCalibrationRequest:type_name -> TrackerGetCalibrationRequest
	20, // 11: Request.trackerStartTrackingRequest:type_name -> TrackerStartTrackingRequest
	21, // 12: Request.trackerGetMarkerLocationRequest:type_name -> TrackerGetMarkerLocationRequest
	23, // 13: Request.trackerUpdateMarkerLocationRequest:type_name -> TrackerUpdateMarkerLocationRequest
	5,  // 14: Response.ackResponse:type_name -> AckResponse
	8,  // 15: Response.getAssetResponse:type_name -> GetAssetResponse
	10, // 16: Response.getTableConfigurationResponse:type_name -> GetTableConfigurationResponse
	12, // 17: Response.getCurrentSceneResponse:type_name -> GetCurrentSceneResponse
	15, // 18: Response.trackerGetStatusResponse:type_name -> TrackerGetStatusResponse
	19, // 19: Response.trackerGetCalibrationResponse:type_name -> TrackerGetCalibrationResponse
	22, // 20: Response.trackerGetMarkerLocationResponse:type_name -> TrackerGetMarkerLocationResponse
	27, // 21: DisplaySceneRequest.scene:type_name -> Scene
	24, // 22: GetTableConfigurationResponse.resolution:type_name -> GetTableConfigurationResponse.Resolution
	27, // 23: GetCurrentSceneResponse.scene:type_name -> Scene
	0,  // 24: TrackerGetStatusResponse.state:type_name -> TrackerGetStatusResponse.TrackerState
	14, // 25: TrackerStartCalibrationRequest.corners:type_name -> TrackerVector2d
	14, // 26: TrackerGetCalibrationResponse.cornerLocations:type_name -> TrackerVector2d
	25, // 27: TrackerGetMarkerLocationResponse.markerLocations:type_name -> TrackerGetMarkerLocationResponse.MarkerLocationsEntry
	26, // 28: TrackerUpdateMarkerLocationRequest.markerLocations:type_name -> TrackerUpdateMarkerLocationRequest.MarkerLocationsEntry
	14, // 29: TrackerGetMarkerLocationResponse.MarkerLocationsEntry.value:type_name -> TrackerVector2d
	14, // 30: TrackerUpdateMarkerLocationRequest.MarkerLocationsEntry.value:type_name -> TrackerVector2d
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_protos_external_proto_init() }
func file_protos_external_proto_init() {
	if File_protos_external_proto != nil {
		return
	}
	file_protos_scene_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_external_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisplaySceneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTableConfigurationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTableConfigurationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentSceneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentSceneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackerGetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackerVector2D); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackerGetStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackerSetIdleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackerStartCalibrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackerGetCalibrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackerGetCalibrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackerStartTrackingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackerGetMarkerLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackerGetMarkerLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackerUpdateMarkerLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTableConfigurationResponse_Resolution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_external_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Packet_Request)(nil),
		(*Packet_Response)(nil),
	}
	file_protos_external_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Request_HelloRequest)(nil),
		(*Request_DisplaySceneRequest)(nil),
		(*Request_GetAssetRequest)(nil),
		(*Request_GetTableConfigurationRequest)(nil),
		(*Request_GetCurrentSceneRequest)(nil),
		(*Request_TrackerGetStatusRequest)(nil),
		(*Request_TrackerSetIdleRequest)(nil),
		(*Request_TrackerStartCalibrationRequest)(nil),
		(*Request_TrackerGetCalibrationRequest)(nil),
		(*Request_TrackerStartTrackingRequest)(nil),
		(*Request_TrackerGetMarkerLocationRequest)(nil),
		(*Request_TrackerUpdateMarkerLocationRequest)(nil),
	}
	file_protos_external_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Response_AckResponse)(nil),
		(*Response_GetAssetResponse)(nil),
		(*Response_GetTableConfigurationResponse)(nil),
		(*Response_GetCurrentSceneResponse)(nil),
		(*Response_TrackerGetStatusResponse)(nil),
		(*Response_TrackerGetCalibrationResponse)(nil),
		(*Response_TrackerGetMarkerLocationResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_external_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_external_proto_goTypes,
		DependencyIndexes: file_protos_external_proto_depIdxs,
		EnumInfos:         file_protos_external_proto_enumTypes,
		MessageInfos:      file_protos_external_proto_msgTypes,
	}.Build()
	File_protos_external_proto = out.File
	file_protos_external_proto_rawDesc = nil
	file_protos_external_proto_goTypes = nil
	file_protos_external_proto_depIdxs = nil
}
