// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: protos/external.proto

package tracker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// Types that are assignable to Message:
	//
	//	*Packet_Request
	//	*Packet_Response
	Message isPacket_Message `protobuf_oneof:"message"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (m *Packet) GetMessage() isPacket_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *Packet) GetRequest() *Request {
	if x, ok := x.GetMessage().(*Packet_Request); ok {
		return x.Request
	}
	return nil
}

func (x *Packet) GetResponse() *Response {
	if x, ok := x.GetMessage().(*Packet_Response); ok {
		return x.Response
	}
	return nil
}

type isPacket_Message interface {
	isPacket_Message()
}

type Packet_Request struct {
	Request *Request `protobuf:"bytes,10,opt,name=request,proto3,oneof"`
}

type Packet_Response struct {
	Response *Response `protobuf:"bytes,11,opt,name=response,proto3,oneof"`
}

func (*Packet_Request) isPacket_Message() {}

func (*Packet_Response) isPacket_Message() {}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*Request_HelloRequest
	//	*Request_DisplaySceneRequest
	//	*Request_GetAssetRequest
	//	*Request_GetTableConfigurationRequest
	//	*Request_GetCurrentSceneRequest
	Message isRequest_Message `protobuf_oneof:"message"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{1}
}

func (m *Request) GetMessage() isRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *Request) GetHelloRequest() *HelloRequest {
	if x, ok := x.GetMessage().(*Request_HelloRequest); ok {
		return x.HelloRequest
	}
	return nil
}

func (x *Request) GetDisplaySceneRequest() *DisplaySceneRequest {
	if x, ok := x.GetMessage().(*Request_DisplaySceneRequest); ok {
		return x.DisplaySceneRequest
	}
	return nil
}

func (x *Request) GetGetAssetRequest() *GetAssetRequest {
	if x, ok := x.GetMessage().(*Request_GetAssetRequest); ok {
		return x.GetAssetRequest
	}
	return nil
}

func (x *Request) GetGetTableConfigurationRequest() *GetTableConfigurationRequest {
	if x, ok := x.GetMessage().(*Request_GetTableConfigurationRequest); ok {
		return x.GetTableConfigurationRequest
	}
	return nil
}

func (x *Request) GetGetCurrentSceneRequest() *GetCurrentSceneRequest {
	if x, ok := x.GetMessage().(*Request_GetCurrentSceneRequest); ok {
		return x.GetCurrentSceneRequest
	}
	return nil
}

type isRequest_Message interface {
	isRequest_Message()
}

type Request_HelloRequest struct {
	// Respond with AckResponse
	HelloRequest *HelloRequest `protobuf:"bytes,1,opt,name=helloRequest,proto3,oneof"`
}

type Request_DisplaySceneRequest struct {
	// Respond with AckResponse
	DisplaySceneRequest *DisplaySceneRequest `protobuf:"bytes,2,opt,name=displaySceneRequest,proto3,oneof"`
}

type Request_GetAssetRequest struct {
	// Respond with GetAssetResponse
	GetAssetRequest *GetAssetRequest `protobuf:"bytes,3,opt,name=getAssetRequest,proto3,oneof"`
}

type Request_GetTableConfigurationRequest struct {
	// Respond with GetTableConfigurationResponse
	GetTableConfigurationRequest *GetTableConfigurationRequest `protobuf:"bytes,4,opt,name=getTableConfigurationRequest,proto3,oneof"`
}

type Request_GetCurrentSceneRequest struct {
	// Respond with GetCurrentSceneResponse
	GetCurrentSceneRequest *GetCurrentSceneRequest `protobuf:"bytes,5,opt,name=getCurrentSceneRequest,proto3,oneof"`
}

func (*Request_HelloRequest) isRequest_Message() {}

func (*Request_DisplaySceneRequest) isRequest_Message() {}

func (*Request_GetAssetRequest) isRequest_Message() {}

func (*Request_GetTableConfigurationRequest) isRequest_Message() {}

func (*Request_GetCurrentSceneRequest) isRequest_Message() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*Response_AckResponse
	//	*Response_GetAssetResponse
	//	*Response_GetTableConfigurationResponse
	//	*Response_GetCurrentSceneResponse
	Message isResponse_Message `protobuf_oneof:"message"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{2}
}

func (m *Response) GetMessage() isResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *Response) GetAckResponse() *AckResponse {
	if x, ok := x.GetMessage().(*Response_AckResponse); ok {
		return x.AckResponse
	}
	return nil
}

func (x *Response) GetGetAssetResponse() *GetAssetResponse {
	if x, ok := x.GetMessage().(*Response_GetAssetResponse); ok {
		return x.GetAssetResponse
	}
	return nil
}

func (x *Response) GetGetTableConfigurationResponse() *GetTableConfigurationResponse {
	if x, ok := x.GetMessage().(*Response_GetTableConfigurationResponse); ok {
		return x.GetTableConfigurationResponse
	}
	return nil
}

func (x *Response) GetGetCurrentSceneResponse() *GetCurrentSceneResponse {
	if x, ok := x.GetMessage().(*Response_GetCurrentSceneResponse); ok {
		return x.GetCurrentSceneResponse
	}
	return nil
}

type isResponse_Message interface {
	isResponse_Message()
}

type Response_AckResponse struct {
	AckResponse *AckResponse `protobuf:"bytes,1,opt,name=ackResponse,proto3,oneof"`
}

type Response_GetAssetResponse struct {
	GetAssetResponse *GetAssetResponse `protobuf:"bytes,2,opt,name=getAssetResponse,proto3,oneof"`
}

type Response_GetTableConfigurationResponse struct {
	GetTableConfigurationResponse *GetTableConfigurationResponse `protobuf:"bytes,3,opt,name=getTableConfigurationResponse,proto3,oneof"`
}

type Response_GetCurrentSceneResponse struct {
	GetCurrentSceneResponse *GetCurrentSceneResponse `protobuf:"bytes,4,opt,name=getCurrentSceneResponse,proto3,oneof"`
}

func (*Response_AckResponse) isResponse_Message() {}

func (*Response_GetAssetResponse) isResponse_Message() {}

func (*Response_GetTableConfigurationResponse) isResponse_Message() {}

func (*Response_GetCurrentSceneResponse) isResponse_Message() {}

type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{3}
}

type AckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{4}
}

type DisplaySceneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scene *Scene `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
}

func (x *DisplaySceneRequest) Reset() {
	*x = DisplaySceneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisplaySceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplaySceneRequest) ProtoMessage() {}

func (x *DisplaySceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplaySceneRequest.ProtoReflect.Descriptor instead.
func (*DisplaySceneRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{5}
}

func (x *DisplaySceneRequest) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

type GetAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{6}
}

func (x *GetAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload   []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	MediaType string `protobuf:"bytes,3,opt,name=mediaType,proto3" json:"mediaType,omitempty"`
}

func (x *GetAssetResponse) Reset() {
	*x = GetAssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetResponse) ProtoMessage() {}

func (x *GetAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetResponse.ProtoReflect.Descriptor instead.
func (*GetAssetResponse) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{7}
}

func (x *GetAssetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAssetResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetAssetResponse) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type GetTableConfigurationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTableConfigurationRequest) Reset() {
	*x = GetTableConfigurationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTableConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableConfigurationRequest) ProtoMessage() {}

func (x *GetTableConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetTableConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{8}
}

type GetTableConfigurationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resolution       *GetTableConfigurationResponse_Resolution `protobuf:"bytes,1,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Size             float64                                   `protobuf:"fixed64,2,opt,name=size,proto3" json:"size,omitempty"`
	PlayAudioOnTable bool                                      `protobuf:"varint,3,opt,name=playAudioOnTable,proto3" json:"playAudioOnTable,omitempty"`
}

func (x *GetTableConfigurationResponse) Reset() {
	*x = GetTableConfigurationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTableConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableConfigurationResponse) ProtoMessage() {}

func (x *GetTableConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetTableConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{9}
}

func (x *GetTableConfigurationResponse) GetResolution() *GetTableConfigurationResponse_Resolution {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *GetTableConfigurationResponse) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetTableConfigurationResponse) GetPlayAudioOnTable() bool {
	if x != nil {
		return x.PlayAudioOnTable
	}
	return false
}

type GetCurrentSceneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCurrentSceneRequest) Reset() {
	*x = GetCurrentSceneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSceneRequest) ProtoMessage() {}

func (x *GetCurrentSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSceneRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentSceneRequest) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{10}
}

type GetCurrentSceneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scene *Scene `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
}

func (x *GetCurrentSceneResponse) Reset() {
	*x = GetCurrentSceneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSceneResponse) ProtoMessage() {}

func (x *GetCurrentSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSceneResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentSceneResponse) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{11}
}

func (x *GetCurrentSceneResponse) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

type GetTableConfigurationResponse_Resolution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  float64 `protobuf:"fixed64,1,opt,name=width,proto3" json:"width,omitempty"`
	Height float64 `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GetTableConfigurationResponse_Resolution) Reset() {
	*x = GetTableConfigurationResponse_Resolution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_external_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTableConfigurationResponse_Resolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableConfigurationResponse_Resolution) ProtoMessage() {}

func (x *GetTableConfigurationResponse_Resolution) ProtoReflect() protoreflect.Message {
	mi := &file_protos_external_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableConfigurationResponse_Resolution.ProtoReflect.Descriptor instead.
func (*GetTableConfigurationResponse_Resolution) Descriptor() ([]byte, []int) {
	return file_protos_external_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetTableConfigurationResponse_Resolution) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetTableConfigurationResponse_Resolution) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_protos_external_proto protoreflect.FileDescriptor

var file_protos_external_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x01, 0x0a, 0x06,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x89,
	0x03, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x0c, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x0c, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x48, 0x0a, 0x13, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x44,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x13, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0f, 0x67, 0x65, 0x74,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x63, 0x0a, 0x1c, 0x67, 0x65, 0x74, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x1c,
	0x67, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x51, 0x0a, 0x16,
	0x67, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x16, 0x67, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xc6, 0x02, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x61, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x10, 0x67, 0x65, 0x74,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x10, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x1d, 0x67, 0x65,
	0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x1d, 0x67, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x54, 0x0a, 0x17, 0x67, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x17, 0x67, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x33, 0x0a, 0x13, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x05, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5a, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xe6, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x41,
	0x75, 0x64, 0x69, 0x6f, 0x4f, 0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x4f, 0x6e, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x1a, 0x3a, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22,
	0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x05, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x75, 0x74, 0x6d, 0x61, 0x6e, 0x39, 0x36, 0x2f, 0x66, 0x61, 0x6e, 0x74, 0x61, 0x73,
	0x73, 0x69, 0x73, 0x74, 0x2e, 0x69, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_external_proto_rawDescOnce sync.Once
	file_protos_external_proto_rawDescData = file_protos_external_proto_rawDesc
)

func file_protos_external_proto_rawDescGZIP() []byte {
	file_protos_external_proto_rawDescOnce.Do(func() {
		file_protos_external_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_external_proto_rawDescData)
	})
	return file_protos_external_proto_rawDescData
}

var file_protos_external_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protos_external_proto_goTypes = []any{
	(*Packet)(nil),                                   // 0: Packet
	(*Request)(nil),                                  // 1: Request
	(*Response)(nil),                                 // 2: Response
	(*HelloRequest)(nil),                             // 3: HelloRequest
	(*AckResponse)(nil),                              // 4: AckResponse
	(*DisplaySceneRequest)(nil),                      // 5: DisplaySceneRequest
	(*GetAssetRequest)(nil),                          // 6: GetAssetRequest
	(*GetAssetResponse)(nil),                         // 7: GetAssetResponse
	(*GetTableConfigurationRequest)(nil),             // 8: GetTableConfigurationRequest
	(*GetTableConfigurationResponse)(nil),            // 9: GetTableConfigurationResponse
	(*GetCurrentSceneRequest)(nil),                   // 10: GetCurrentSceneRequest
	(*GetCurrentSceneResponse)(nil),                  // 11: GetCurrentSceneResponse
	(*GetTableConfigurationResponse_Resolution)(nil), // 12: GetTableConfigurationResponse.Resolution
	(*Scene)(nil),                                    // 13: Scene
}
var file_protos_external_proto_depIdxs = []int32{
	1,  // 0: Packet.request:type_name -> Request
	2,  // 1: Packet.response:type_name -> Response
	3,  // 2: Request.helloRequest:type_name -> HelloRequest
	5,  // 3: Request.displaySceneRequest:type_name -> DisplaySceneRequest
	6,  // 4: Request.getAssetRequest:type_name -> GetAssetRequest
	8,  // 5: Request.getTableConfigurationRequest:type_name -> GetTableConfigurationRequest
	10, // 6: Request.getCurrentSceneRequest:type_name -> GetCurrentSceneRequest
	4,  // 7: Response.ackResponse:type_name -> AckResponse
	7,  // 8: Response.getAssetResponse:type_name -> GetAssetResponse
	9,  // 9: Response.getTableConfigurationResponse:type_name -> GetTableConfigurationResponse
	11, // 10: Response.getCurrentSceneResponse:type_name -> GetCurrentSceneResponse
	13, // 11: DisplaySceneRequest.scene:type_name -> Scene
	12, // 12: GetTableConfigurationResponse.resolution:type_name -> GetTableConfigurationResponse.Resolution
	13, // 13: GetCurrentSceneResponse.scene:type_name -> Scene
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_protos_external_proto_init() }
func file_protos_external_proto_init() {
	if File_protos_external_proto != nil {
		return
	}
	file_protos_scene_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_external_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DisplaySceneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetAssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetTableConfigurationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetTableConfigurationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GetCurrentSceneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetCurrentSceneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_external_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GetTableConfigurationResponse_Resolution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_external_proto_msgTypes[0].OneofWrappers = []any{
		(*Packet_Request)(nil),
		(*Packet_Response)(nil),
	}
	file_protos_external_proto_msgTypes[1].OneofWrappers = []any{
		(*Request_HelloRequest)(nil),
		(*Request_DisplaySceneRequest)(nil),
		(*Request_GetAssetRequest)(nil),
		(*Request_GetTableConfigurationRequest)(nil),
		(*Request_GetCurrentSceneRequest)(nil),
	}
	file_protos_external_proto_msgTypes[2].OneofWrappers = []any{
		(*Response_AckResponse)(nil),
		(*Response_GetAssetResponse)(nil),
		(*Response_GetTableConfigurationResponse)(nil),
		(*Response_GetCurrentSceneResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_external_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_external_proto_goTypes,
		DependencyIndexes: file_protos_external_proto_depIdxs,
		MessageInfos:      file_protos_external_proto_msgTypes,
	}.Build()
	File_protos_external_proto = out.File
	file_protos_external_proto_rawDesc = nil
	file_protos_external_proto_goTypes = nil
	file_protos_external_proto_depIdxs = nil
}
